// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef configwindow_h
#define configwindow_h
#include <FL/Fl.H>
#include "config_observable.h"
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Input.H>

class ConfigWindowFactory : ConfigObservable {
public:
  Fl_Window* make_window();
  Fl_Window *ConfigWindow;
private:
  inline void cb_Apply_i(Fl_Button*, void*);
  static void cb_Apply(Fl_Button*, void*);
public:
  Fl_Value_Input *AccountIdInput;
  void addObserver(const ConfigObserver &observer);
};
#endif
