// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef config_window_factory_h
#define config_window_factory_h
#include <FL/Fl.H>
#include <map>
#include <string>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>

class ConfigWindowFactory {
public:
  Fl_Window* make_window();
  Fl_Window *ConfigWindow;
private:
  inline void cb_Apply_i(Fl_Button*, void*);
  static void cb_Apply(Fl_Button*, void*);
public:
  Fl_Input *AccountIdInput;
};
#endif
